export let originalData = [
  {
    "id": 1,
    "group_id": 1,
    "count": 1,
    "title": "TEST1 ",
    "sentence": " David denied__the money.",
    "options": "stealing,to steal",
    "answer": "stealing",
    "analysis": "deny 「否认」 后接动名词，表示 「否认做过某事」。",
    "remark": "【 永春高中】",
    "have_video": 1,
    "is_collect": true
  },
  {
    "id": 2,
    "group_id": 1,
    "count": 2,
    "title": "TEST1 ",
    "sentence": " __he told you isn’t true.",
    "options": "What,Whether",
    "answer": "What",
    "analysis": "What he told you isn’ t true. 他告诉你的不是真的。 What 为复合，引导名词子句（名词性从句）做主词(主语)。",
    "remark": "【 西松高中】",
    "have_video": 2,
    "is_collect": false
  },
  {
    "id": 3,
    "group_id": 1,
    "count": 3,
    "title": "TEST1 ",
    "sentence": " Are you going to leave the door__?",
    "options": "opened,open",
    "answer": "open",
    "analysis": "「 leave+ 受词（宾语） + 受词补语（宾语补语）」表 「把～置于… 状态」， leave the door open指 「让门开着（ 没有关） 」， 补语用形容词 open 「开着的」， 表状态。",
    "remark": "【 三重高中】",
    "have_video": 3,
    "is_collect": false
  },
  {
    "id": 4,
    "group_id": 1,
    "count": 4,
    "title": "TEST1 ",
    "sentence": " Please keep the door__.",
    "options": "closed,close",
    "answer": "closed",
    "analysis": "keep the door closed 让门关着（ 不要打开） ， closed 为形 容词。 close 当动词表 「关闭」， 当形容词是 「靠近的」， 句 意、用法皆不合",
    "remark": "",
    "have_video": 4,
    "is_collect": false
  },
  {
    "id": 5,
    "group_id": 1,
    "count": 5,
    "title": "TEST1 ",
    "sentence": " What__you cry?",
    "options": "caused,made",
    "answer": "made",
    "analysis": "由受词(宾语)后的原形动词可知， 空格需要使役动词(表示使...让...的含义,如have, let, make) made。 caused 为一般动词， 接受词（宾语）后要用 to do 。",
    "remark": "【 永平高中】",
    "have_video": 5,
    "is_collect": true
  },
  {
    "id": 6,
    "group_id": 1,
    "count": 6,
    "title": "TEST1 ",
    "sentence": " __things carefully.",
    "options": "Observe,To observe",
    "answer": "Observe",
    "analysis": "Observe things carefully. 要小心观察事物。 命令句用原形动词。",
    "remark": "【北京大学】",
    "have_video": 6,
    "is_collect": true
  },
  {
    "id": 7,
    "group_id": 1,
    "count": 7,
    "title": "TEST1 ",
    "sentence": " Do you feel like__for a swim?",
    "options": "to go,going",
    "answer": "going",
    "analysis": "feel like doing 想要做某事 ,go for a swim 去游泳（= go swimming）",
    "remark": "【陝西大学】",
    "have_video": 7,
    "is_collect": false
  },
  {
    "id": 8,
    "group_id": 1,
    "count": 8,
    "title": "TEST1 ",
    "sentence": " I’ ll be back__ten minutes.",
    "options": "in,after",
    "answer": "in",
    "analysis": "in 用于未来式， 表示 「再过...时间」。",
    "remark": "【日本爱知工大】",
    "have_video": 8,
    "is_collect": false
  },
  {
    "id": 9,
    "group_id": 1,
    "count": 9,
    "title": "TEST1 ",
    "sentence": " __anything happens, call me immediately.",
    "options": "In case,Even though",
    "answer": "In case",
    "analysis": "In case anything happens, call me immediately. 万一有任何事情发生， 立刻打电话给我。1.in case 万一； 如果（ 表示条件时候等于if） 2. even though即使；虽然（表让步时候等于though）",
    "remark": "【 四川大学】",
    "have_video": 9,
    "is_collect": false
  },
  {
    "id": 10,
    "group_id": 1,
    "count": 10,
    "title": "TEST1 ",
    "sentence": " She sat__her children.",
    "options": "surrounded by,surrounding",
    "answer": "surrounded by",
    "analysis": "She sat surrounded by her children. 她坐着被她的小孩包围。 依句意为「被动」，用 surrounded by... 做补语。",
    "remark": "【 日本西南院大】",
    "have_video": 10,
    "is_collect": false
  },
  {
    "id": 11,
    "group_id": 1,
    "count": 11,
    "title": "TEST1 ",
    "sentence": " __Sunday, the bank was closed.",
    "options": "Being,It being",
    "answer": "It being",
    "analysis": "It being Sunday, the bank was closed. 因为是周日， 银行没开。 前句原为 Because it was Sunday， 改成分词构句时， 主词(主语)it 和后句 the bank 不同， 故保留。",
    "remark": "【日本北海学园大】",
    "have_video": 11,
    "is_collect": false
  },
  {
    "id": 12,
    "group_id": 1,
    "count": 12,
    "title": "TEST1 ",
    "sentence": " __ill,I stayed at home.",
    "options": "Being,It being",
    "answer": "Being",
    "analysis": "前句原为 Because I was ill， 改成分词构句时， 主词（主句）和后句相同， 故省略。",
    "remark": "",
    "have_video": 12,
    "is_collect": false
  },
  {
    "id": 13,
    "group_id": 1,
    "count": 13,
    "title": "TEST1 ",
    "sentence": " It is essential that you__there today.",
    "options": "are,be",
    "answer": "be",
    "analysis": "It is essential 后的 that 子句中，助动词 should 常省略， 用原形动词，表示「 … 是必须的」。",
    "remark": "【 日本樱美林大】",
    "have_video": 13,
    "is_collect": false
  },
  {
    "id": 14,
    "group_id": 1,
    "count": 14,
    "title": "TEST1 ",
    "sentence": " There is __the future.",
    "options": "no predicting,not to predict",
    "answer": "no predicting",
    "analysis": "There is no predicting the future. 未来是无法预测的。 There is no+ doing 做～是不可能的 （= It is impossible to do ）",
    "remark": "【 成功高中】",
    "have_video": 14,
    "is_collect": false
  },
  {
    "id": 15,
    "group_id": 1,
    "count": 15,
    "title": "TEST1 ",
    "sentence": "I generally__many dogs near my school.",
    "options": "see,am seeing",
    "answer": "see",
    "analysis": "generally 「一般； 通常」 和现在式连用。",
    "remark": "【 日本明治大】",
    "have_video": 15,
    "is_collect": false
  },
  {
    "id": 16,
    "group_id": 1,
    "count": 16,
    "title": "TEST1 ",
    "sentence": " I have no idea when he__again.",
    "options": "come,will come",
    "answer": "will come",
    "analysis": "when 引导名词子句（名词性从句）， 做I have no idea= I don’ t know 的受词（宾语）， 依句意该 用未来式。",
    "remark": "【 日本玉川大】",
    "have_video": 16,
    "is_collect": false
  },
  {
    "id": 17,
    "group_id": 1,
    "count": 17,
    "title": "TEST1 ",
    "sentence": " They__in Tokyo tomorrow.",
    "options": "will be arrived,are arriving",
    "answer": "are arriving",
    "analysis": "arrive 「到达」 为来去动词， 可用现在进行式表未来。 arrive 为不及物动词， 没有被动。",
    "remark": "【 日本东北学院大 】",
    "have_video": 17,
    "is_collect": true
  },
  {
    "id": 18,
    "group_id": 1,
    "count": 18,
    "title": "TEST1 ",
    "sentence": " It__time to learn a new language.",
    "options": "spends,takes",
    "answer": "takes",
    "analysis": "It是虚主词(不是真正主语)， 后面的不定词(不定式)是真正主词(主语)， 表示事物「花」时间用 takes。",
    "remark": "【 三重高中】",
    "have_video": 18,
    "is_collect": false
  },
  {
    "id": 19,
    "group_id": 1,
    "count": 19,
    "title": "TEST1 ",
    "sentence": " The king is not kind__cruel.",
    "options": "only,but",
    "answer": "but",
    "analysis": "not A but B 不是A 而是B",
    "remark": "【 育成高中】",
    "have_video": 19,
    "is_collect": false
  },
  {
    "id": 20,
    "group_id": 1,
    "count": 20,
    "title": "TEST1 ",
    "sentence": " The movie is worth__.",
    "options": "to be seen,seeing",
    "answer": "seeing",
    "analysis": "be worth+ doing「值得～」 有三个条件：1.doing 为主动 2.及物动词3.无受词(宾语)。",
    "remark": "【 成功高中】",
    "have_video": 20,
    "is_collect": false
  }
]